<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/attendance.php');
	include_once(__DIR__ . '/attendance_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('attendance');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'attendance';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`attendance`.`attID`" => "attID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpID`), CONCAT_WS('',   `employees1`.`EmpID`), '') /* EmpID */" => "empID",
		"IF(    CHAR_LENGTH(`employees1`.`name`), CONCAT_WS('',   `employees1`.`name`), '') /* Name */" => "name",
		"if(`attendance`.`date`,date_format(`attendance`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`attendance`.`time_in`, '%r')" => "time_in",
		"TIME_FORMAT(`attendance`.`time_out`, '%r')" => "time_out",
		"`attendance`.`day_of_week`" => "day_of_week",
		"`attendance`.`hours_worked`" => "hours_worked",
		"`attendance`.`is_late`" => "is_late",
		"`attendance`.`early_out`" => "early_out",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`attendance`.`attID`',
		2 => '`employees1`.`EmpID`',
		3 => '`employees1`.`name`',
		4 => '`attendance`.`date`',
		5 => '`attendance`.`time_in`',
		6 => '`attendance`.`time_out`',
		7 => 7,
		8 => '`attendance`.`hours_worked`',
		9 => 9,
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`attendance`.`attID`" => "attID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpID`), CONCAT_WS('',   `employees1`.`EmpID`), '') /* EmpID */" => "empID",
		"IF(    CHAR_LENGTH(`employees1`.`name`), CONCAT_WS('',   `employees1`.`name`), '') /* Name */" => "name",
		"if(`attendance`.`date`,date_format(`attendance`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`attendance`.`time_in`, '%r')" => "time_in",
		"TIME_FORMAT(`attendance`.`time_out`, '%r')" => "time_out",
		"`attendance`.`day_of_week`" => "day_of_week",
		"`attendance`.`hours_worked`" => "hours_worked",
		"`attendance`.`is_late`" => "is_late",
		"`attendance`.`early_out`" => "early_out",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`attendance`.`attID`" => "AttID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpID`), CONCAT_WS('',   `employees1`.`EmpID`), '') /* EmpID */" => "EmpID",
		"IF(    CHAR_LENGTH(`employees1`.`name`), CONCAT_WS('',   `employees1`.`name`), '') /* Name */" => "Name",
		"`attendance`.`date`" => "Date",
		"`attendance`.`time_in`" => "Time in",
		"`attendance`.`time_out`" => "Time out",
		"`attendance`.`day_of_week`" => "Day of week",
		"`attendance`.`hours_worked`" => "Hours worked",
		"`attendance`.`is_late`" => "Is late",
		"`attendance`.`early_out`" => "Early out",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`attendance`.`attID`" => "attID",
		"IF(    CHAR_LENGTH(`employees1`.`EmpID`), CONCAT_WS('',   `employees1`.`EmpID`), '') /* EmpID */" => "empID",
		"IF(    CHAR_LENGTH(`employees1`.`name`), CONCAT_WS('',   `employees1`.`name`), '') /* Name */" => "name",
		"if(`attendance`.`date`,date_format(`attendance`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`attendance`.`time_in`, '%r')" => "time_in",
		"TIME_FORMAT(`attendance`.`time_out`, '%r')" => "time_out",
		"`attendance`.`day_of_week`" => "day_of_week",
		"`attendance`.`hours_worked`" => "hours_worked",
		"`attendance`.`is_late`" => "is_late",
		"`attendance`.`early_out`" => "early_out",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['empID' => 'EmpID', ];

	$x->QueryFrom = "`attendance` LEFT JOIN `employees` as employees1 ON `employees1`.`EmpID`=`attendance`.`empID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'attendance_view.php';
	$x->TableTitle = 'Attendance';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`attendance`.`attID`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['EmpID', 'Name', 'Date', 'Time in', 'Time out', 'Day of week', 'Hours worked', 'Is late', 'Early out', ];
	$x->ColFieldName = ['empID', 'name', 'date', 'time_in', 'time_out', 'day_of_week', 'hours_worked', 'is_late', 'early_out', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/attendance_templateTV.html';
	$x->SelectedTemplate = 'templates/attendance_templateTVS.html';
	$x->TemplateDV = 'templates/attendance_templateDV.html';
	$x->TemplateDVP = 'templates/attendance_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: attendance_init
	$render = true;
	if(function_exists('attendance_init')) {
		$args = [];
		$render = attendance_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: attendance_header
	$headerCode = '';
	if(function_exists('attendance_header')) {
		$args = [];
		$headerCode = attendance_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: attendance_footer
	$footerCode = '';
	if(function_exists('attendance_footer')) {
		$args = [];
		$footerCode = attendance_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
