<?php

// Data functions (insert, update, delete, form) for table attendance

// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function attendance_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('attendance');
	if(!$arrPerm['insert']) return false;

	$data = [
		'empID' => Request::lookup('empID', ''),
		'name' => Request::lookup('empID'),
		'date' => Request::dateComponents('date', '1'),
		'time_in' => parseCode('<%%creationTime%%>', true, true),
	];


	// hook: attendance_before_insert
	if(function_exists('attendance_before_insert')) {
		$args = [];
		if(!attendance_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('attendance', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('attendance', $recID, calculated_fields()['attendance']);

	// hook: attendance_after_insert
	if(function_exists('attendance_after_insert')) {
		$res = sql("SELECT * FROM `attendance` WHERE `attID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!attendance_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('attendance', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) attendance_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function attendance_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function attendance_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('attendance', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: attendance_before_delete
	if(function_exists('attendance_before_delete')) {
		$args = [];
		if(!attendance_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `attendance` WHERE `attID`='{$selected_id}'", $eo);

	// hook: attendance_after_delete
	if(function_exists('attendance_after_delete')) {
		$args = [];
		attendance_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='attendance' AND `pkValue`='{$selected_id}'", $eo);
}

function attendance_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('attendance', $selected_id, 'edit')) return false;

	$data = [
		'empID' => Request::lookup('empID', ''),
		'name' => Request::lookup('empID'),
		'date' => Request::dateComponents('date', ''),
	];

	// get existing values
	$old_data = getRecord('attendance', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: attendance_before_update
	if(function_exists('attendance_before_update')) {
		$args = ['old_data' => $old_data];
		if(!attendance_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'attendance', 
		backtick_keys_once($set), 
		['`attID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="attendance_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('attendance', $data['selectedID'], calculated_fields()['attendance']);

	// hook: attendance_after_update
	if(function_exists('attendance_after_update')) {
		$res = sql("SELECT * FROM `attendance` WHERE `attID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['attID'];
		$args = ['old_data' => $old_data];
		if(!attendance_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='attendance' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function attendance_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('attendance');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_empID = Request::val('filterer_empID');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: empID
	$combo_empID = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = defined('attendance.date.MinYear') ? constant('attendance.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('attendance.date.MaxYear') ? constant('attendance.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: is_late
	$combo_is_late = new Combo;
	$combo_is_late->ListType = 0;
	$combo_is_late->MultipleSeparator = ', ';
	$combo_is_late->ListBoxHeight = 10;
	$combo_is_late->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/attendance.is_late.csv')) {
		$is_late_data = addslashes(implode('', @file(__DIR__ . '/hooks/attendance.is_late.csv')));
		$combo_is_late->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($is_late_data))));
		$combo_is_late->ListData = $combo_is_late->ListItem;
	} else {
		$combo_is_late->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("yes;;no"))));
		$combo_is_late->ListData = $combo_is_late->ListItem;
	}
	$combo_is_late->SelectName = 'is_late';

	if($selected_id) {
		if(!check_record_permission('attendance', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('attendance', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('attendance', $selected_id, 'delete');

		$res = sql("SELECT * FROM `attendance` WHERE `attID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'attendance_view.php', false);
		}
		$combo_empID->SelectedData = $row['empID'];
		$combo_date->DefaultDate = $row['date'];
		$combo_is_late->SelectedData = $row['is_late'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_empID->SelectedData = $filterer_empID;
		$combo_is_late->SelectedText = (isset($filterField[1]) && $filterField[1] == '9' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_empID->HTML = '<span id="empID-container' . $rnd1 . '"></span><input type="hidden" name="empID" id="empID' . $rnd1 . '" value="' . html_attr($combo_empID->SelectedData) . '">';
	$combo_empID->MatchText = '<span id="empID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="empID" id="empID' . $rnd1 . '" value="' . html_attr($combo_empID->SelectedData) . '">';
	$combo_is_late->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_empID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['empID'] : htmlspecialchars($filterer_empID, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(empID_reload__RAND__) == 'function') empID_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function empID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#empID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_empID__RAND__.value, t: 'attendance', f: 'empID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="empID"]').val(resp.results[0].id);
							$j('[id=empID-container-readonly__RAND__]').html('<span class="match-text" id="empID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }


							if(typeof(empID_update_autofills__RAND__) == 'function') empID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'attendance', f: 'empID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_empID__RAND__.value = e.added.id;
				AppGini.current_empID__RAND__.text = e.added.text;
				$j('[name="empID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }


				if(typeof(empID_update_autofills__RAND__) == 'function') empID_update_autofills__RAND__();
			});

			if(!$j("#empID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_empID__RAND__.value, t: 'attendance', f: 'empID' },
					success: function(resp) {
						$j('[name="empID"]').val(resp.results[0].id);
						$j('[id=empID-container-readonly__RAND__]').html('<span class="match-text" id="empID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }

						if(typeof(empID_update_autofills__RAND__) == 'function') empID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_empID__RAND__.value, t: 'attendance', f: 'empID' },
				success: function(resp) {
					$j('[id=empID-container__RAND__], [id=empID-container-readonly__RAND__]').html('<span class="match-text" id="empID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }

					if(typeof(empID_update_autofills__RAND__) == 'function') empID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/attendance_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/attendance_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Attendance details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return attendance_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return attendance_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return attendance_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#empID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#empID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(empID)%%>', $combo_empID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(empID)%%>', $combo_empID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(empID)%%>', urlencode($combo_empID->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(date)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : 
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(is_late)%%>', $combo_is_late->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(is_late)%%>', $combo_is_late->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['empID' => ['employees', 'EmpID'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(attID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(empID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time_in)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time_out)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(day_of_week)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hours_worked)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(is_late)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(early_out)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(attID)%%>', safe_html($urow['attID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(attID)%%>', html_attr($row['attID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(attID)%%>', urlencode($urow['attID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(empID)%%>', safe_html($urow['empID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(empID)%%>', html_attr($row['empID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empID)%%>', urlencode($urow['empID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_in)%%>', time12(html_attr($row['time_in'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_in)%%>', urlencode(time12($urow['time_in'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_out)%%>', time12(html_attr($row['time_out'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_out)%%>', urlencode(time12($urow['time_out'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(day_of_week)%%>', safe_html($urow['day_of_week']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(day_of_week)%%>', urlencode($urow['day_of_week']), $templateCode);
		$templateCode = str_replace('<%%VALUE(hours_worked)%%>', safe_html($urow['hours_worked']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hours_worked)%%>', urlencode($urow['hours_worked']), $templateCode);
		$templateCode = str_replace('<%%VALUE(is_late)%%>', safe_html($urow['is_late']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(is_late)%%>', urlencode($urow['is_late']), $templateCode);
		$templateCode = str_replace('<%%VALUE(early_out)%%>', safe_html($urow['early_out']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(early_out)%%>', urlencode($urow['early_out']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(attID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(attID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(empID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(empID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_in)%%>', '<%%creationTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_in)%%>', urlencode('<%%creationTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_out)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_out)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(day_of_week)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(day_of_week)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hours_worked)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hours_worked)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(is_late)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(is_late)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(early_out)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(early_out)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tempID_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'attendance_autofill.php?rnd1=$rnd1&mfk=empID&id=' + encodeURIComponent('".addslashes($row['empID'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'attendance_autofill.php?rnd1=$rnd1&mfk=empID&id=' + encodeURIComponent(AppGini.current_empID{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#empID$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#empID$rnd1').prop('disabled', false); " : "\$j('#empID$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#empID_caption').length) \$j('#empID_caption').click(function() { empID_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('attendance');
	if($selected_id) {
		$jdata = get_joined_record('attendance', $selected_id);
		if($jdata === false) $jdata = get_defaults('attendance');
		$rdata = $row;
	}
	$templateCode .= loadView('attendance-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: attendance_dv
	if(function_exists('attendance_dv')) {
		$args = [];
		attendance_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}