<?php

// Data functions (insert, update, delete, form) for table employees

// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function employees_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('employees');
	if(!$arrPerm['insert']) return false;

	$data = [
		'name' => Request::val('name', ''),
		'department' => Request::val('department', ''),
		'position' => Request::val('position', ''),
		'fingerprint1' => Request::val('fingerprint1', ''),
		'fingerprint_2' => Request::val('fingerprint_2', ''),
		'fingerprint_3' => Request::val('fingerprint_3', ''),
		'date_enrolled' => Request::dateComponents('date_enrolled', ''),
	];


	// hook: employees_before_insert
	if(function_exists('employees_before_insert')) {
		$args = [];
		if(!employees_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('employees', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('employees', $recID, calculated_fields()['employees']);

	// hook: employees_after_insert
	if(function_exists('employees_after_insert')) {
		$res = sql("SELECT * FROM `employees` WHERE `EmpID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!employees_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('employees', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) employees_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function employees_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function employees_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('employees', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: employees_before_delete
	if(function_exists('employees_before_delete')) {
		$args = [];
		if(!employees_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: roll_call
	$res = sql("SELECT `EmpID` FROM `employees` WHERE `EmpID`='{$selected_id}'", $eo);
	$EmpID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `roll_call` WHERE `empID`='" . makeSafe($EmpID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'roll_call', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'roll_call', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'employees_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'employees_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: insights
	$res = sql("SELECT `EmpID` FROM `employees` WHERE `EmpID`='{$selected_id}'", $eo);
	$EmpID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `insights` WHERE `empID`='" . makeSafe($EmpID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'insights', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'insights', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'employees_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'employees_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `employees` WHERE `EmpID`='{$selected_id}'", $eo);

	// hook: employees_after_delete
	if(function_exists('employees_after_delete')) {
		$args = [];
		employees_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='employees' AND `pkValue`='{$selected_id}'", $eo);
}

function employees_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('employees', $selected_id, 'edit')) return false;

	$data = [
		'name' => Request::val('name', ''),
		'department' => Request::val('department', ''),
		'position' => Request::val('position', ''),
		'fingerprint1' => Request::val('fingerprint1', ''),
		'fingerprint_2' => Request::val('fingerprint_2', ''),
		'fingerprint_3' => Request::val('fingerprint_3', ''),
		'date_enrolled' => Request::dateComponents('date_enrolled', ''),
	];

	// get existing values
	$old_data = getRecord('employees', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: employees_before_update
	if(function_exists('employees_before_update')) {
		$args = ['old_data' => $old_data];
		if(!employees_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'employees', 
		backtick_keys_once($set), 
		['`EmpID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="employees_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('employees', $data['selectedID'], calculated_fields()['employees']);

	// hook: employees_after_update
	if(function_exists('employees_after_update')) {
		$res = sql("SELECT * FROM `employees` WHERE `EmpID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['EmpID'];
		$args = ['old_data' => $old_data];
		if(!employees_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='employees' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function employees_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('employees');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date_enrolled
	$combo_date_enrolled = new DateCombo;
	$combo_date_enrolled->DateFormat = "mdy";
	$combo_date_enrolled->MinYear = defined('employees.date_enrolled.MinYear') ? constant('employees.date_enrolled.MinYear') : 1900;
	$combo_date_enrolled->MaxYear = defined('employees.date_enrolled.MaxYear') ? constant('employees.date_enrolled.MaxYear') : 2100;
	$combo_date_enrolled->DefaultDate = parseMySQLDate('', '');
	$combo_date_enrolled->MonthNames = $Translation['month names'];
	$combo_date_enrolled->NamePrefix = 'date_enrolled';

	if($selected_id) {
		if(!check_record_permission('employees', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('employees', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('employees', $selected_id, 'delete');

		$res = sql("SELECT * FROM `employees` WHERE `EmpID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'employees_view.php', false);
		}
		$combo_date_enrolled->DefaultDate = $row['date_enrolled'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/employees_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/employees_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Employee details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return employees_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return employees_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return employees_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#department').replaceWith('<div class=\"form-control-static\" id=\"department\">' + (jQuery('#department').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#position').replaceWith('<div class=\"form-control-static\" id=\"position\">' + (jQuery('#position').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fingerprint1').replaceWith('<div class=\"form-control-static\" id=\"fingerprint1\">' + (jQuery('#fingerprint1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fingerprint_2').replaceWith('<div class=\"form-control-static\" id=\"fingerprint_2\">' + (jQuery('#fingerprint_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fingerprint_3').replaceWith('<div class=\"form-control-static\" id=\"fingerprint_3\">' + (jQuery('#fingerprint_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#date_enrolled').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#date_enrolledDay, #date_enrolledMonth, #date_enrolledYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(date_enrolled)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date_enrolled->GetHTML(true) . '</div>' : 
			$combo_date_enrolled->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_enrolled)%%>', $combo_date_enrolled->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(EmpID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(department)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(position)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fingerprint1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fingerprint_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fingerprint_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_enrolled)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(EmpID)%%>', safe_html($urow['EmpID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(EmpID)%%>', html_attr($row['EmpID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EmpID)%%>', urlencode($urow['EmpID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(department)%%>', safe_html($urow['department']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(department)%%>', html_attr($row['department']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(department)%%>', urlencode($urow['department']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(position)%%>', safe_html($urow['position']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(position)%%>', html_attr($row['position']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(position)%%>', urlencode($urow['position']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fingerprint1)%%>', safe_html($urow['fingerprint1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fingerprint1)%%>', html_attr($row['fingerprint1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint1)%%>', urlencode($urow['fingerprint1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fingerprint_2)%%>', safe_html($urow['fingerprint_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fingerprint_2)%%>', html_attr($row['fingerprint_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint_2)%%>', urlencode($urow['fingerprint_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fingerprint_3)%%>', safe_html($urow['fingerprint_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fingerprint_3)%%>', html_attr($row['fingerprint_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint_3)%%>', urlencode($urow['fingerprint_3']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_enrolled)%%>', app_datetime($row['date_enrolled']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_enrolled)%%>', urlencode(app_datetime($urow['date_enrolled'])), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(EmpID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EmpID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(department)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(department)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(position)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(position)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fingerprint1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fingerprint_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fingerprint_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fingerprint_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_enrolled)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_enrolled)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('employees');
	if($selected_id) {
		$jdata = get_joined_record('employees', $selected_id);
		if($jdata === false) $jdata = get_defaults('employees');
		$rdata = $row;
	}
	$templateCode .= loadView('employees-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: employees_dv
	if(function_exists('employees_dv')) {
		$args = [];
		employees_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}