<?php
// This script and data application were generated by AppGini 23.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('roll_call');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'empID':
			if(!$id) {
				?>
				$j('#name<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `employees`.`EmpID` as 'EmpID', `employees`.`name` as 'name', `employees`.`department` as 'department', `employees`.`position` as 'position', `employees`.`fingerprint1` as 'fingerprint1', `employees`.`fingerprint_2` as 'fingerprint_2', `employees`.`fingerprint_3` as 'fingerprint_3', if(`employees`.`date_enrolled`,date_format(`employees`.`date_enrolled`,'%m/%d/%Y'),'') as 'date_enrolled' FROM `employees`  WHERE `employees`.`EmpID`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#name<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['name']))); ?>&nbsp;');
			<?php
			break;


	}

?>